# Testing Parameters:
SEED: 42
LOAD_PATH: './result/imface++_neutral'
DATA_PATH: './demo'
GT_PATH: './demo'
VOX_RESOLUTION: 256
CALCULATE_ERROR: True
GPUS: '0'
BATCH_SPLIT: 20000
RESUME:

LOSS:
  SDF_LOSS_PROGRESS: [ [ 0.2, 3000.0 ], [ 0.5, 0 ] ]
  NORMAL_LOSS_PROGRESS: [ [ 0.2, 100.0 ], [ 0.5, 0 ] ]
  EIKONAL_LOSS_OBSERVATION_PROGRESS: [ [ 0.2, 50.0 ], [ 0.5, 0 ] ]
  EIKONAL_LOSS_CANONICAL_PROGRESS: [ [ 0.2, 50.0 ], [ 0.5, 0 ] ]
  ID_EMBEDDING_REGULARIZATION_PROGRESS: [[0.2, 100000.0], [0.5, 0]]
  EXP_EMBEDDING_REGULARIZATION_PROGRESS: [[0.2, 100000.0], [0.5, 0]]
  RESIDUAL_SDF_PROGRESS: [ [ 0.2,0 ],[ 0.5, 3000 ],[ 1.0, 3000 ] ]
  RESIDUAL_NORMAL_LOSS_PROGRESS: [ [ 0.2,0 ],[ 0.5, 100 ],[ 1.0, 100 ] ]
  RESIDUAL_EIKONAL_LOSS_OBSERVATION_PROGRESS: [ [ 0.2,0 ],[ 0.5, 50 ],[ 1.0, 50 ] ]
  RESIDUAL_EIKONAL_LOSS_CANONICAL_PROGRESS: [ [ 0.2,0 ],[ 0.5, 50 ],[ 1.0, 50 ] ]
  DETAIL_EMBEDDING_REGULARIZATION_PROGRESS: [[0.2, 0], [0.5, 1000], [1.0, 1000]]

OPTIMIZATION:
  INITIAL_STD: 0.01
  AMP: False
  TEST_NUM: 1
  LOG_INTERVAL: 50
  BATCH_SIZE: 1
  NUM_EPOCHS: 1500
  LR_BEGIN_DECAY: 200
  LR: 1.0e-4
  LR_INTERVAL: 10
  LR_DECAY: 0.95
  detail_embeddings: [ [ 0.2, 0.0 ],[ 0.5,1.0 ],[ 1, 0.01 ] ]
  embeddings: [ [ 0.2, 1.0 ], [ 0.5,0.0 ], [ 1, 0.0 ] ]



