# Training Parameters:
data_path: 'dataset/Facescape'
save_path: 'result/'
fit_list: 'config/list/test_facescape_pub.txt'
gt_path: 'dataset/Facescape'
load_path: ''
gpus: '7'


exp_types: [ 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 ] # 20
keypoint_type: 'full'
sample_func: 'random_sample_full'
batch_size: 16 # 72
log_frequency: 50
test_obj_num: 2

# Testing Parameters:
voxel_resolution: 256
points_per_inference: 163840
grid_radius: 1

# Hyper Parameters:
epoch: 1500
sdf_clamp: 0.5
lr_begin_decay: 200
lr_decoder: 1.0e-4
lr_interval: 10
lr_factor: 0.95
sample_num: 16384

network_params:
  warp_type: 'translation'
  model_type: 'sine'
  id_embedding_dim: 128
  exp_embedding_dim: 128
  id_hyper_hidden_layers: 1
  exp_hyper_hidden_layers: 1
  id_hyper_hidden_features: 128
  exp_hyper_hidden_features: 128
  id_hidden_dim: 128
  exp_hidden_dim: 128
  id_num_hidden_layers: 3
  exp_num_hidden_layers: 3
  deform_pe: False
  reference_pe: False
  template_pe: False
  num_encoding_functions: 6

  training_losses: # NO INTER LOSS
    sdf: 3000.0
    normal_constraint: 100.0
    eikonal_constraint_drt: 50.0
    # eikonal_constraint_rt: 50.0
    # eikonal_constraint_t: 50.0
    keypoints_refer_constraint: 100.0
    id_embeddings_constraint: 1000000.0
    exp_embeddings_constraint: 1000000.0